/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/assets/minecraft_hammer.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.02, 4.09, 0]} rotation={[0, 0, 1.97]}>
        <mesh
          geometry={nodes.Hammer_1.geometry}
          material={materials.material_3}
        />
        <mesh
          geometry={nodes.Hammer_2.geometry}
          material={materials.material_2}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/minecraft_hammer.glb");
